[SYSTEM]
# WEB3_MODE = TRUE  : enable Anvil / smart contract event listener
# WEB3_MODE = FALSE : use Web2 simulation mode for the course project
WEB3_MODE = TRUE

[CHAIN]
RPC_URL = http://127.0.0.1:8546
CHAIN_ID = 31337
CHAIN_NAME = Anvil Local
CURRENCY_SYMBOL = ETH
CONTRACT_ADDRESS = 0x5FbDB2315678afecb367f032d93F642f64180aa3
DEMO_ETH_PRICE = 20000


